version: '3.9'  # Updated to the latest stable version

services:
  cassandra:
    container_name: cassandra
    image: cassandra:latest
    restart: unless-stopped
    ports:
      - "${CASSANDRA_PORT:-9042}:9042"  # External port configurable via environment variables
    environment:
      - CASSANDRA_USER=${CASSANDRA_USER:-admin}  # Credentials using environment variables
      - CASSANDRA_PASSWORD_FILE=/run/secrets/cassandra_password  # Using Docker secrets for passwords
    volumes:
      - cassandra-data:/var/lib/cassandra  # Volume for data persistence
    networks:
      - tools-net
      - external-net    # External network for communication from host machine
    secrets:
      - cassandra_password  # Reference to Docker secret
    healthcheck:
      test: ["CMD", "cqlsh", "-u", "${CASSANDRA_USER:-admin}", "-p", "/run/secrets/cassandra_password", "--execute", "SELECT now()"]
      interval: 30s
      retries: 5
      timeout: 10s
      start_period: 10s  # Added start period to avoid false failures immediately after start

secrets:
  cassandra_password:
    external: true  # Assumes the secret has been created externally with `docker secret create`

volumes:
  cassandra-data:
    driver: local  # Ensuring consistent volume driver

networks:
  tools-net:
    driver: bridge  # Consistent with internal network setup

  external-net:
    driver: bridge    # External communication from the host machine