version: '3.9'  # Updated to the latest stable version

services:
  ##############################################################
  ### Kafka/Zookeeper
  ##############################################################
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    ports:
      - 2181:2181
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data  # Use volume for data persistence
    networks:
      - tools-net
      - external-net    # External network for communication from host machine
    healthcheck:
      test: ["CMD", "zkCli.sh", "-server", "localhost:2181", "ls", "/"]
      interval: 30s
      retries: 5
      timeout: 10s

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 9093:9093
    restart: unless-stopped
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka-data:/var/lib/kafka/data  # Use volume for data persistence
    networks:
      - tools-net
      - external-net    # External network for communication from host machine
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "kafka:9092", "--list"]
      interval: 30s
      retries: 5
      timeout: 10s

volumes:
  zookeeper-data:
    driver: local  # Ensuring consistent volume driver
  kafka-data:
    driver: local  # Ensuring consistent volume driver

networks:
  tools-net:
    driver: bridge  # Consistent with internal network setup

  external-net:
    driver: bridge    # External communication from the host machine