package eu.isygoit.enums;

/**
 * AWS KMS Key Origin alignment.
 * <p>
 * Represents the source of key material as defined by AWS KMS.
 * </p>
 * @see <a href="https://docs.aws.amazon.com/kms/latest/APIReference/API_KeyMetadata.html#KMS-Type-KeyMetadata-Origin">AWS Origin</a>
 */
public interface IEnumKeyOrigin {

    int STR_ENUM_SIZE = 4;

    /**
     * AWS KMS key origin types.
     */
    enum Types implements IEnum {

        /**
         * Key material generated by WAMS KMS (default).
         */
        WAMS_KMS("WAMS_KMS"),

        /**
         * Key material imported by the customer (Bring Your Own Key – BYOK).
         */
        EXTERNAL("EXTERNAL"),

        /**
         * Key material generated in an AWS CloudHSM custom key store.
         */
        AWS_CLOUDHSM("AWS_CLOUDHSM"),

        /**
         * Key material managed in an external key store (XKS) proxy.
         */
        EXTERNAL_KEY_STORE("EXTERNAL_KEY_STORE");

        private final String meaning;

        Types(String meaning) {
            this.meaning = meaning;
        }

        @Override
        public String meaning() {
            return meaning;
        }
    }
}