package eu.isygoit.enums;

/**
 * WAMS KMS Key Origin alignment.
 * <p>
 * Represents the source of key material as defined by WAMS KMS.
 * </p>
 */
public interface IEnumKeyOrigin {

    int STR_ENUM_SIZE = 4;

    /**
     * WAMS KMS key origin types.
     */
    enum Types implements IEnum {

        /**
         * Key material generated by WAMS KMS (default).
         * - Cannot expire; lifecycle is managed via rotation.
         * - Supports automatic rotation.
         * - Backed internally by KMS storage.
         * - Supports direct deletion.
         * - Default pending deletion period: 30 days.
         */
        WAMS_KMS("WAMS_KMS", false, true, false, true, 30),

        /**
         * Key material imported by the customer (Bring Your Own Key – BYOK).
         * - Supports expiration. Once expiration date passes, key material is deleted.
         * - Does NOT support rotation (KMS does not own the original material).
         * - Backed by KMS storage (imported material is stored securely).
         * - Supports direct deletion.
         * - Default pending deletion period: 7 days (shorter due to external origin).
         */
        EXTERNAL("EXTERNAL", true, false, false, true, 7),

        /**
         * Key material generated in a WAMS CloudHSM custom key store.
         * - Cannot expire under KMS control; expiration may be handled internally by HSM.
         * - Supports rotation (HSM can generate new key versions).
         * - Requires external backup (HSM cluster backup is separate from KMS).
         * - Supports deletion (KMS can delete key from HSM).
         * - Default pending deletion period: 30 days.
         */
        WAMS_CLOUDHSM("WAMS_CLOUDHSM", false, true, true, true, 30),

        /**
         * Key material managed in an external key store (XKS) proxy.
         * - Cannot expire from KMS perspective; expiration is delegated to the external system.
         * - Does NOT support rotation (handled by external proxy if at all).
         * - Requires external backup (external system manages durability).
         * - Does NOT support direct deletion (delegated to external proxy).
         * - Default pending deletion period: 0 (not applicable; deletion must be handled externally).
         */
        EXTERNAL_KEY_STORE("EXTERNAL_KEY_STORE", false, false, true, false, 0);

        private final String meaning;
        private final boolean canExpire;
        private final boolean supportsRotation;
        private final boolean requiresExternalBackup;
        private final boolean supportsDeletion;
        private final int defaultPendingDeletionDays;

        Types(String meaning,
              boolean canExpire,
              boolean supportsRotation,
              boolean requiresExternalBackup,
              boolean supportsDeletion,
              int defaultPendingDeletionDays) {
            this.meaning = meaning;
            this.canExpire = canExpire;
            this.supportsRotation = supportsRotation;
            this.requiresExternalBackup = requiresExternalBackup;
            this.supportsDeletion = supportsDeletion;
            this.defaultPendingDeletionDays = defaultPendingDeletionDays;
        }

        @Override
        public String meaning() {
            return meaning;
        }

        /**
         * Returns whether keys of this origin can have an expiration date.
         * Only EXTERNAL origin typically supports expiration in a KMS.
         *
         * @return true if expiration is supported, false otherwise
         */
        public boolean canExpire() {
            return canExpire;
        }

        /**
         * Returns whether the KMS can automatically rotate key material for this origin.
         * Typically false for imported and external-store keys.
         *
         * @return true if rotation is supported, false otherwise
         */
        public boolean supportsRotation() {
            return supportsRotation;
        }

        /**
         * Returns whether the key's durability relies on external backup systems
         * (e.g., CloudHSM cluster backup, external key store proxy).
         *
         * @return true if external backup is required, false if KMS handles durability
         */
        public boolean requiresExternalBackup() {
            return requiresExternalBackup;
        }

        /**
         * Returns whether the KMS can directly delete the key material.
         * For EXTERNAL_KEY_STORE, deletion may need to be performed by the external proxy.
         *
         * @return true if the KMS supports direct deletion, false otherwise
         */
        public boolean supportsDeletion() {
            return supportsDeletion;
        }

        /**
         * Returns the default pending deletion period (in days) recommended for this origin.
         * Used when scheduling key deletion.
         *
         * @return number of days to wait before permanent deletion
         */
        public int getDefaultPendingDeletionDays() {
            return defaultPendingDeletionDays;
        }
    }
}