package eu.isygoit.enums;

/**
 * WAMS KMS Key Origin alignment.
 *
 * Represents the source of key material as defined by WAMS KMS.
 */
public interface IEnumKeyOrigin {

    int STR_ENUM_SIZE = 4;

    /**
     * WAMS KMS key origin types.
     */
    enum Types implements IEnum {

        /**
         * Key material generated by WAMS KMS.
         */
        WAMS_KMS("WAMS_KMS"),

        /**
         * Key material imported by the customer (BYOK).
         */
        EXTERNAL("EXTERNAL"),

        /**
         * Key material generated in WAMS CloudHSM custom key store.
         */
        WAMS_CLOUDHSM("WAMS_CLOUDHSM"),

        /**
         * Key material managed in an external key store (XKS).
         */
        EXTERNAL_KEY_STORE("EXTERNAL_KEY_STORE");

        private final String meaning;

        Types(String meaning) {
            this.meaning = meaning;
        }

        @Override
        public String meaning() {
            return meaning;
        }
    }
}